name: build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distribution: [ 'zulu', 'adopt', 'liberica' ]
        java-version: [ '11.0.0', '11.0.1', '11.0.2', '11.0.3', '11.0.4', '11.0.5', '11.0.6', '11.0.7', '11.0.8', '11.0.9', '11.0.10', '11.0.11', '11.0.12', '11.0.13', '11.0.14' ]
        exclude:
          - distribution: zulu
            java-version: 11.0.0
        include:
          - distribution: temurin
            java-version: 11.0.12
          - distribution: temurin
            java-version: 11.0.13
          - distribution: temurin
            java-version: 11.0.14
          - distribution: microsoft
            java-version: 11.0.13

    name: ${{ matrix.distribution }} JDK ${{ matrix.java-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up ${{ matrix.distribution }} JDK ${{ matrix.java-version }}
      id: setup-java
      uses: actions/setup-java@v2
      continue-on-error: true
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distribution }}
    - name: Build with javac
      if: ${{ steps.setup-java.outcome == 'success' }}
      run: javac -Xdiags:verbose MethodReferenceBug.java
